test

diff --git a/.github/workflows/ci-comment.yml b/.github/workflows/ci-comment.yml
--- a/.github/workflows/ci-comment.yml
+++ b/.github/workflows/ci-comment.yml
@@ -35,6 +35,12 @@ jobs:
             echo "No previous comment found in cache"
           fi
 
+      - name: Bench
+        id: curr-bench
+        run: |
+          content=$(cat output.txt | jq -R -s .)
+          echo "BENCH_RESULT=$content" >> $GITHUB_OUTPUT
+
       - name: Trigger n8n webhook
         if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
         id: webhook
@@ -48,12 +54,13 @@ jobs:
 
           response=$(curl -f -X POST ${{ secrets.N8N_WEBHOOK_URL }} \
           -H "Content-Type: application/json" \
-          -d "{
-            \"repo\": \"${{ github.repository }}\",
-            \"pr_number\": \"${{ github.event.pull_request.number }}\",
-            \"commit_id\": \"${{ github.sha }}\",
-            \"prev_comment_id\": \"${prev_comment_id}\"
-          }" || echo "CURL_ERROR")
+          -d '{
+            "repo": "${{ github.repository }}",
+            "pr_number": "${{ github.event.pull_request.number }}",
+            "commit_id": "${{ github.sha }}",
+            "bench_result": ${{ steps.curr-bench.outputs.BENCH_RESULT }},
+            "prev_comment_id": "'"${prev_comment_id}"'"
+          }' || echo "CURL_ERROR")
 
           if [ "$response" = "CURL_ERROR" ]; then
             echo "::error::Failed to trigger n8n webhook"
